[workspace]
members = [
    "encoding",
    "device",
]

[profile.dev]
opt-level = "s"

[profile.release]
debug = true

[patch.crates-io]
lora-phy = { git = "https://github.com/jbeaurivage/lora-phy.git", branch = "nimbus-board-type" }
